Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: key

# This metric is hard to grasp but let's avoid delirious code
Metrics/AbcSize:
  Max: 60

Metrics/MethodLength:
  Max: 40

# This is Chef names
Naming/FileName:
  Exclude:
  - Policyfile.rb

# We don't write documentation there at the moment
Style/Documentation:
  Enabled: false

# This requires to add a comment inside nearly all file which could be
# considered as toil without value
Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
