name             'smbios'
maintainer       'Criteo'
maintainer_email 'hardware@criteo.com'
license          'All rights reserved'
description      'Get Smbios info'
long_description 'Get Smbios info'
issues_url       'https://github.com/criteo-cookbooks/smbios/issues'
source_url       'https://github.com/criteo-cookbooks/smbios'
version          '0.1.0'
supports         'centos'
supports         'windows'
