# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: smbios
# Spec:: default
#
# Copyright:: 2018, The Authors, All Rights Reserved.

require 'spec_helper'

describe 'smbios::default' do
  [
    { platform: 'centos', version: '7.8.2003' },
    { platform: 'windows', version: '2016' },
  ].each do |settings|
    context "When all attributes are default, on #{settings[:platform]} #{settings[:version]}" do
      let(:chef_run) { ::ChefSpec::SoloRunner.new(settings).converge(described_recipe) }

      it('converges successfully') { chef_run }
    end
  end
end
